### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by DarylDixonLS** [GTG2K16/GT-MP_GM#1]
Hab das mal getestet aus langerweile ;) das ergebnis ;)

2018-02-06 04:42:30.5332 |  Info | Bmx | Los Santos AirPort Fahrad Spawn 
2018-02-06 04:42:30.5432 |  Info | Program | Started! Waiting for connections. 
2018-02-06 04:42:31.2990 | Error | ScriptingEngine | EXCEPTION IN RESOURCE GtG_World_RP1 INSIDE SCRIPTENGINE DatabaseManager System.Data.Entity.Core.ProviderIncompatibleException: The provider did not return a ProviderManifestToken string. ---> MySql.Data.MySqlClient.MySqlException: Unable to connect to any of the specified MySQL hosts. ---> System.Net.Sockets.SocketException: Der angegebene Host ist unbekannt
   bei System.Net.Dns.GetAddrInfo(String name)
   bei System.Net.Dns.InternalGetHostByName(String hostName, Boolean includeIPv6)
   bei System.Net.Dns.GetHostEntry(String hostNameOrAddress)
   bei MySql.Data.Common.MyNetworkStream.CreateStream(MySqlConnectionStringBuilder settings, Boolean unix)
   bei MySql.Data.Common.StreamCreator.GetStream(MySqlConnectionStringBuilder settings)
   bei MySql.Data.MySqlClient.NativeDriver.Open()
   --- Ende der internen Ausnahmestapelüberwachung ---
   bei MySql.Data.MySqlClient.NativeDriver.Open()
   bei MySql.Data.MySqlClient.Driver.Open()
   bei MySql.Data.MySqlClient.Driver.Create(MySqlConnectionStringBuilder settings)
   bei MySql.Data.MySqlClient.MySqlPool.GetPooledConnection()
   bei MySql.Data.MySqlClient.MySqlPool.TryToGetDriver()
   bei MySql.Data.MySqlClient.MySqlPool.GetConnection()
   bei MySql.Data.MySqlClient.MySqlConnection.Open()
   bei MySql.Data.MySqlClient.MySqlProviderServices.GetDbProviderManifestToken(DbConnection connection)
   bei System.Data.Entity.Core.Common.DbProviderServices.GetProviderManifestToken(DbConnection connection)
   --- Ende der internen Ausnahmestapelüberwachung ---
   bei System.Data.Entity.Core.Common.DbProviderServices.GetProviderManifestToken(DbConnection connection)
   bei System.Data.Entity.Utilities.DbConnectionExtensions.GetProviderInfo(DbConnection connection, DbProviderManifest& providerManifest)
   bei System.Data.Entity.DbModelBuilder.Build(DbConnection providerConnection)
   bei System.Data.Entity.Internal.LazyInternalContext.CreateModel(LazyInternalContext internalContext)
   bei System.Data.Entity.Internal.RetryLazy`2.GetValue(TInput input)
   bei System.Data.Entity.Internal.LazyInternalContext.InitializeContext()
   bei System.Data.Entity.Internal.InternalContext.Initialize()
   bei System.Data.Entity.Internal.InternalContext.GetEntitySetAndBaseTypeForType(Type entityType)
   bei System.Data.Entity.Internal.Linq.InternalSet`1.Initialize()
   bei System.Data.Entity.Internal.Linq.InternalSet`1.get_InternalContext()
   bei System.Data.Entity.Infrastructure.DbQuery`1.System.Linq.IQueryable.get_Provider()
   bei System.Linq.Queryable.Count[TSource](IQueryable`1 source)
   bei GTG_World_RP.Server.Datenbank.DatabaseManager.OnResourceStart()
   bei GrandTheftMultiplayer.Server.Models.ScriptingEngine.<InvokeResourceStart>b__26_0()
   bei GrandTheftMultiplayer.Server.Models.ScriptingEngine.MainThreadLoop()

**Comment by SaschaP1802** [comment]
Hast du den auch Alle Strings für die Datenbank Angepasst und einen Webserver auf dem die Login Sachen sind? Der Fehler Besagt
MySql.Data.MySqlClient.MySqlException: Unable to connect to any of the specified MySQL hosts. ---> System.Net.Sockets.SocketException: **Der angegebene Host ist unbekannt**

**Comment by DarylDixonLS** [comment]
ja myaql.inc.php
<?php
$sql = array();
$sql['host'] = "localhost";
$sql['user'] = "*****";
$sql['pwd'] = "******";
$sql['db'] = "******";

$sql['mysql_error'] = "Verbindung zum PROXY IceLand konnte nicht hergestellt wurden.";
$sql['db_error'] = "Verbindung zur Proxy Databasis konnte nicht hergestellt werden.";
?>

ist angepasst
sowie die Database.manager.cs 
            //ContextFactory.SetConnectionParameters("localhost", "******", "******", "****");
            ContextFactory.SetConnectionParameters("IP:127.0.0.1", "DbUser", "DbPasswort", "Datenbank");

**Comment by SaschaP1802** [comment]
Die Zeile 27 muss angepasst werden nicht die 26

**Comment by DarylDixonLS** [comment]
^^ wtf*

**Comment by DarylDixonLS** [comment]
bei der registration erscheint nun eine leere seite http://*****.de/gta/"RegAccount?socialclub=&token=" in der Register.php finde ich nichts dazu...
:(

**Comment by SaschaP1802** [comment]
Der fehler heißt das die DB Konfig falsch ist, es ist alles auf MySqli diese Erweiterung sollte auf deinem WebSpace Aktiviert sein ansonsten musst du das abändern auf MySql.

**Comment by DarylDixonLS** [comment]
ok da lass ich es mal lieber ^^ aber danke für die infos.. solltet ihr ggf. mit in die readme schreiben ;)

**Comment by SaschaP1802** [comment]
Es kann aber auch Möglich sein das nur deine Config Falsch ist das diese Datenbank auf localhost nicht Existiert!

**Comment by DarylDixonLS** [comment]
ich teste es noch ein mal mit ner anderen datenbank... aber ich glaube nicht das es funktioniert.. sag gleich mal bescheid

**Comment by DarylDixonLS** [comment]
so getestet klappt nicht :( schade..

**Comment by DarylDixonLS** [comment]
Aber er hat zumindestens:
  | benutzerprofiel | 
  | characters | 
  | vehicles |
  |__migrationhistory |  
in der Datenbank angelegt ;)

**Comment by SaschaP1802** [comment]
Ja gut das bedeutet einfach nur das du in der login.php register.php die Datenbank Strings anpassen musst an das veraltete System MySql statt MySqli,
Und wie gesagt solltest du nicht das root folder nutzen musst du im GM dein Subfolder angeben. 
Dann klappt das auch alles!

**Comment by DarylDixonLS** [comment]
ok ;) ne ich lasse es mal lieber das ist nicht meine materie sonst hab ich zum schluss noch ne Waschmaschine draus gebaut ;) hab mir das mal mit mysqli angeschaut und schon herzrasen bekommen ^^ aber werde mir mal deine version im auge behalten ggf. findet sich ein anderer der dies hinbekommt ;)

**Comment by DarylDixonLS** [comment]
Ok. Hab noch einmal geschaut in die php.ini
Dort ist folgendes aktiviert:
extension=php_mysql.dll
extension=php_mysqli.dll

Laut http://www.php.net/manual/de/mysqli.installation.php ist dies aktiviert...

**Comment by DarylDixonLS** [comment]
Zumindestens greift er jetzt schon mal auf den server ;)
http://www.bilder-upload.eu/upload/bb20d9-1518201406.jpg

**Comment by SaschaP1802** [comment]
Es geht vorran!

**Comment by DarylDixonLS** [comment]
ja aber ich bekomm immer die seite angezeigt angeblich sei dort nix obwohl alles auf die domaine geht ^^ muss ggf. noch irgendwas eingestellt werden?
Falls du mal Zeit hast ggf. zu helfen ;)
https://discord.gg/3xJbz9N

**Comment by SaschaP1802** [comment]
Wie ist es denn aufgebaut wie sieht die Struktur aus und die Settings im GM so wie in der Meta.xml?

**Comment by DarylDixonLS** [comment]
nein die meta hab ich angepasst.

**Comment by SaschaP1802** [comment]
Also es wurde von mehreren getestet und funktioniert soweit bei denjenigen Windows Server wie auch Linux Server sowohl WebClient Linux oder Windows alles Funktions fähig

# Close
